import {  Montserrat } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { Provider } from 'react-redux';
import store from '../../redux/store';


const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <html>
      <body className={montserrat.className}>
    <div className="">
    <Navbar/>
      <main className=''> {children}</main>
    </div>
  </body>
  </html>
  )
}
